// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.8.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `codec_for`, `current_tuning`, `downmix_f32`, `downmix_i16`, `downmix_u16`, `play_waveform_cpal`, `resample_linear`, `start_listening_cpal`

double get encodeSampleRate => RustLib.instance.api.crateApiEncodeSampleRate();

BigInt get playbackTailMs => RustLib.instance.api.crateApiPlaybackTailMs();

Future<void> initRust() => RustLib.instance.api.crateApiInitRust();

Future<void> setUltrasonicFreq({required double freqStart}) =>
    RustLib.instance.api.crateApiSetUltrasonicFreq(freqStart: freqStart);

Future<Float32List> encode({
  required List<int> data,
  required int protocolId,
  required int volume,
}) => RustLib.instance.api.crateApiEncode(
  data: data,
  protocolId: protocolId,
  volume: volume,
);

Future<void> startListening({required int protocolId}) =>
    RustLib.instance.api.crateApiStartListening(protocolId: protocolId);

Future<void> stopListening() => RustLib.instance.api.crateApiStopListening();

Future<void> playWaveform({required List<double> waveform}) =>
    RustLib.instance.api.crateApiPlayWaveform(waveform: waveform);

Stream<Uint8List> createOnMessageStream() =>
    RustLib.instance.api.crateApiCreateOnMessageStream();
